# Commands for mkdocs: mkdocs new, mkdocs serve, mkdocs build, mkdocs gh-deploy, mkdocs --help
# Commands for app: 
#   - docker build -t node-todo .         -> "Build the container image"
#   - docker run -dp 3000:3000 node-todo  -> "Start the container"
#   - docker login -u YOUR-USER-NAME      -> "Login to the Docker Hub (https://hub.docker.com). Play with Docker(https://labs.play-with-docker.com/)"
#   - docker tag node-todo YOUR-USER-NAME/node-todo -> "Use the `docker tag` command to give the `node-todo` image a new name"
#   - docker push YOUR-USER-NAME/node-todo  -> "Running the `push command`"

site_name: Feathers OPC UA application
site_url: https://bsa-git.github.io/feathers-opcua-server/

# Configuration
theme:
  name: readthedocs

extra_css:
  - css/styles.css
  - css/dark-mode.css

# Navigation
nav:
  - Home: 
    - 'What is OPC UA?': 'README.md'
  - 'Get started':
    - 'Part1. Getting started': 'tutorial\part1_getting-started\index.md'
    - 'Part2. FeathersJS framework overview': 'tutorial\part2_framework-overview\index.md'
    - 'Part3. Application Features': 'tutorial\part3_app-features\index.md'
    - 'Part4. Resources info': 'tutorial\part4_resources-info\index.md'
    - 'Part5. Installation': 'tutorial\part5_installation\index.md'
    - 'Part6. Configuration': 'tutorial\part6_configuration\index.md'
    - 'Part7. Install as a Windows service': 'tutorial\part7_install-as-win-service\index.md'
  - About:
    - 'License': 'LICENSE.md'
